### ISSUE TITLE
How to train without downloaing the pretrained DA-Net model

### ISSUE THREAD

**Issue by Yi1214** [junfu1115/DANet#75]
Hello, thanks a lot for your beautiful work!

When I try to train your model, it will automatically download the pretrained model even if I set the  **"pretrained = False"**  in  danet.py --def get_danet( ). It still download the zip file like follows:
Downloading ./pretrain_models/resnet101-5be5422a.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet101-5be5422a.zip.

So how can I set to not download the pretrained model,  and use the original resnet-101 in pytorch, not the dilated resnet-101？

**Comment by Dirtybluer** [comment]
> Hello, thanks a lot for your beautiful work!
> 
> When I try to train your model, it will automatically download the pretrained model even if I set the **"pretrained = False"** in danet.py --def get_danet( ). It still download the zip file like follows:
> Downloading ./pretrain_models/resnet101-5be5422a.zip from https://hangzh.s3.amazonaws.com/encoding/models/resnet101-5be5422a.zip.
> 
> So how can I set to not download the pretrained model, and use the original resnet-101 in pytorch, not the dilated resnet-101？

Hi!
As you've discovered, setting the `pretrained = False` in **danet.py:get_danet()** doesn't work, since the downloading process is not triggered by this flag.
Actually, if you'd dig more into the source code, you can find the 'true' pretrained flag is defined in DANet/encoding/models/base.py: line 45 `self.pretrained = resnet.resnet101(pretrained=True, dilated=dilated,
                                               norm_layer=norm_layer, root=root,
                                               multi_grid=multi_grid, multi_dilation=multi_dilation)`
