### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

### ISSUE THREAD

**Issue by InstantWindy** [junfu1115/DANet#82]
Hi. When I run the code, it shows error as follows
'FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja' ' Thanks.

**Comment by zhudahui** [comment]
Have you solved it?

**Comment by lidehuihxjz** [comment]
I also met this error, whether install PyTorch  from conda or source. Anyone knows how to slove this?

**Comment by zhudahui** [comment]
用了pip install ninja，但是后面又出了其他的错，如果你解决了，希望可以加扣扣，1940078219一起探讨




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lidehuihxjz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 晚上6:36
收件人:&nbsp;"junfu1115/DANet"<DANet@noreply.github.com&gt;;
抄送:&nbsp;"我很怪丶"<1940078219@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [junfu1115/DANet] FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja' (#82)




I also met this error, whether install PyTorch  from conda or source. Anyone knows how to slove this?

**Comment by lidehuihxjz** [comment]
> 用了pip install ninja，但是后面又出了其他的错，如果你解决了，希望可以加扣扣，1940078219一起探讨
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lidehuihxjz"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月29日(星期二) 晚上6:36 收件人:&nbsp;"junfu1115/DANet"<DANet@noreply.github.com&gt;; 抄送:&nbsp;"我很怪丶"<1940078219@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [junfu1115/DANet] FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja' (#82) I also met this error, whether install PyTorch from conda or source. Anyone knows how to slove this? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

用了pip install ninja也还是报ninja: build stopped: subcommand failed. 源码安装pytorch和各种版本的都试过了，都不行。想知道有人跑通过这代码吗 [\笑哭]

**Comment by zhudahui** [comment]
看issue上是有人跑通的，可以加个好友，万一谁解决了可以互通


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lidehuihxjz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 上午10:17
收件人:&nbsp;"junfu1115/DANet"<DANet@noreply.github.com&gt;;
抄送:&nbsp;"我很怪丶"<1940078219@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [junfu1115/DANet] FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja' (#82)



 
用了pip install ninja，但是后面又出了其他的错，如果你解决了，希望可以加扣扣，1940078219一起探讨
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lidehuihxjz"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月29日(星期二) 晚上6:36 收件人:&nbsp;"junfu1115/DANet"<DANet@noreply.github.com&gt;; 抄送:&nbsp;"我很怪丶"<1940078219@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [junfu1115/DANet] FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja' (#82) I also met this error, whether install PyTorch from conda or source. Anyone knows how to slove this? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
用了pip install ninja也还是报ninja: build stopped: subcommand failed. 源码安装pytorch和各种版本的都试过了，都不行。想知道有人跑通过这代码吗 [\笑哭]

**Comment by zzx0836** [comment]
用pytorch 版本不一致，用pytorch 0.4
